labellers_name:
  - "samuele"
  - "michele_d"
  - "michele_f"
  - "roberto"
  - "others"

labellers:
  # From 0 to 10 labelled
  michele_d:  {min: 5, max: 10}  # Both included
  samuele:    {min: 11, max: 20}   # Both included
  michele_f:  {min: 21, max: 30}  # Both included
  roberto:    {min: 31, max: 41}  # Both included
