# COCO 2017 dataset http://cocodataset.org
train: ../coco/images/train2017 # 118287 images
val: ../coco/images/val2017  # 5000 images
test: ../coco/images/test2017
anno_path: ../coco/annotations/instances_val2017.json

# number of classes
nc: 4
# whether it is coco dataset, only coco dataset should be set to True.
is_coco: False

# class names
names: ['red_button', 'blue_button',  'red_plug', 'door_handle', 'slider']
